version: '3.8'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '5432:5432'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'